# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grype < Formula
  desc "A vulnerability scanner for container images and filesystems"
  homepage "https://github.com/anchore/grype"
  version "0.47.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anchore/grype/releases/download/v0.47.0/grype_0.47.0_darwin_amd64.tar.gz"
      sha256 "70b6ef6fb305161e2e8d4a198512017342356ff8b2a924649dfab768ec7ac577"

      def install
        bin.install "grype"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anchore/grype/releases/download/v0.47.0/grype_0.47.0_darwin_arm64.tar.gz"
      sha256 "564b503bd7dd43f838662471efcf8be70814ced41e612f89418b713137e3152a"

      def install
        bin.install "grype"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/anchore/grype/releases/download/v0.47.0/grype_0.47.0_linux_amd64.tar.gz"
      sha256 "92fbbc449dfdd11f09c7551a435d3e2b35c4cca1101c7d03f3f6354c9831f08f"

      def install
        bin.install "grype"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anchore/grype/releases/download/v0.47.0/grype_0.47.0_linux_arm64.tar.gz"
      sha256 "d343e03964370f595f413a4c10715d4fea1a76af4e95b4b2a6daaf327d48812a"

      def install
        bin.install "grype"
      end
    end
  end
end
