# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Grype < Formula
  desc "A vulnerability scanner for container images and filesystems"
  homepage "https://github.com/anchore/grype"
  version "0.21.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/anchore/grype/releases/download/v0.21.0/grype_0.21.0_darwin_amd64.zip"
    sha256 "2c921ff76cbf2a1f9796614603179f3cd5abe7c8e4ff197a73c4069c628ecd24"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/anchore/grype/releases/download/v0.21.0/grype_0.21.0_linux_amd64.tar.gz"
    sha256 "16dce50653591e837d36daa67a6aff21a886f7b3c3cb2edcfddbf698bcd9e771"
  end

  def install
    bin.install "grype"

    # Install bash completion
    output = Utils.popen_read("#{bin}/grype completion bash")
    (bash_completion/"grype").write output

    # Install zsh completion
    output = Utils.popen_read("#{bin}/grype completion zsh")
    (zsh_completion/"_grype").write output
  end
end
