# This file was generated by GoReleaser. DO NOT EDIT.
cask "grype" do
  version "0.113.0"

  on_macos do
    on_intel do
      url "https://github.com/anchore/grype/releases/download/v#{version}/grype_#{version}_darwin_amd64.tar.gz"
      sha256 "572b285f46744ce35aac8c5129c90e481d57edca10f7b33362bf8f6f1a6c519a"
    end
    on_arm do
      url "https://github.com/anchore/grype/releases/download/v#{version}/grype_#{version}_darwin_arm64.tar.gz"
      sha256 "5165a43923a6681b3991917ae7f3534bda572ec72176a5fdd6680c6b35873416"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anchore/grype/releases/download/v#{version}/grype_#{version}_linux_amd64.tar.gz"
      sha256 "d87059d11616446a5dd817a47c21823676b4b24bdaac529695ca404a32ba339d"
    end
    on_arm do
      url "https://github.com/anchore/grype/releases/download/v#{version}/grype_#{version}_linux_arm64.tar.gz"
      sha256 "9fb05aff6757913b1c8480a70f2c77f4cc78b03bca3a66d8161ad6136da35462"
    end
  end

  name "grype"
  desc "A vulnerability scanner for container images and filesystems"
  homepage "https://github.com/anchore/grype"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grype"

  # No zap stanza required

end
