# This file was generated by GoReleaser. DO NOT EDIT.
cask "grype" do
  desc "A vulnerability scanner for container images and filesystems"
  homepage "https://github.com/anchore/grype"
  version "0.97.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grype"

  on_macos do
    on_intel do
      url "https://github.com/anchore/grype/releases/download/v0.97.2/grype_0.97.2_darwin_amd64.tar.gz"
      sha256 "9f8d9b92fecbb789f533ae4db90b1201de6df0bf80b8399fda5c9263485560cf"
    end
    on_arm do
      url "https://github.com/anchore/grype/releases/download/v0.97.2/grype_0.97.2_darwin_arm64.tar.gz"
      sha256 "bb344b4638a2009a80f3bba9729c435b0f123f76679b55a83afa718443340dbf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anchore/grype/releases/download/v0.97.2/grype_0.97.2_linux_amd64.tar.gz"
      sha256 "9db8daad914906aae9a2d99c75ed2bde19fb33e5ea3e14e5b814c6029e1034a9"
    end
    on_arm do
      url "https://github.com/anchore/grype/releases/download/v0.97.2/grype_0.97.2_linux_arm64.tar.gz"
      sha256 "a8dcd15dbf42799601b6933d2376c939b6ec9d366568af4c9cbd2201b7d47c18"
    end
  end

  conflicts_with formula: [
      "grype",
    ]

  # No zap stanza required
end
