# This file was generated by GoReleaser. DO NOT EDIT.
cask "grype" do
  name "grype"
  desc "A vulnerability scanner for container images and filesystems"
  homepage "https://github.com/anchore/grype"
  version "0.105.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "grype"

  on_macos do
    on_intel do
      url "https://github.com/anchore/grype/releases/download/v#{version}/grype_#{version}_darwin_amd64.tar.gz"
      sha256 "4db34c69c09e0554eba1226ad754b1a1d4ff2fc28f161ab21f68bd1f67666621"
    end
    on_arm do
      url "https://github.com/anchore/grype/releases/download/v#{version}/grype_#{version}_darwin_arm64.tar.gz"
      sha256 "f64356365655beaf6346ff11c705cceac6c5a9537a96642328b51cd2d8513841"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anchore/grype/releases/download/v#{version}/grype_#{version}_linux_amd64.tar.gz"
      sha256 "3307e0ae2f41ce094b5d9213202f1c553f222f17f944095f7f75f3e2e52235f9"
    end
    on_arm do
      url "https://github.com/anchore/grype/releases/download/v#{version}/grype_#{version}_linux_arm64.tar.gz"
      sha256 "3aed15e0ab3b4dfed59a8c655a5ea30f460c9b07a7a59c8782c2e1903755c327"
    end
  end

  # No zap stanza required
end
